package toolscript

import (
	"compress/gzip"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// The golden corpus under testdata/intl/number is generated by
// internal/intlgen/number/golden.mjs with Node (V8 + ICU); the Goja oracle
// has no Intl, so these services are checked against Node's output.

type intlGoldenCase struct {
	Name string `json:"name"`
	Code string `json:"code"`
	Want string `json:"want"`
}

func loadIntlGolden(t testing.TB, pattern string) map[string][]intlGoldenCase {
	paths, err := filepath.Glob(pattern)
	if err != nil || len(paths) == 0 {
		t.Fatalf("no golden files match %s", pattern)
	}
	sort.Strings(paths)
	out := map[string][]intlGoldenCase{}
	for _, p := range paths {
		f, err := os.Open(p)
		if err != nil {
			t.Fatal(err)
		}
		zr, err := gzip.NewReader(f)
		if err != nil {
			t.Fatal(err)
		}
		var file struct {
			Cases []intlGoldenCase `json:"cases"`
		}
		if err := json.NewDecoder(zr).Decode(&file); err != nil {
			t.Fatalf("%s: %v", p, err)
		}
		f.Close()
		out[strings.TrimSuffix(filepath.Base(p), ".json.gz")] = file.Cases
	}
	return out
}

// Declines are allowed only for these reasons: another numbering system
// than Latin digits, and error texts V8 renders from function source.
var intlAllowedDecline = regexp.MustCompile(`Intl numbering system|Intl error text`)

func runIntlCase(c intlGoldenCase) (string, error) {
	p, err := Compile(c.Code, CompileOptions{Batches: true})
	if err != nil {
		return "", err
	}
	res, err := p.Execute(context.Background(), ExecuteOptions{})
	if err != nil {
		return "", err
	}
	s, ok := res.Value.(string)
	if !ok {
		return "", fmt.Errorf("result is %T, not a string", res.Value)
	}
	return s, nil
}

// jsonDiff describes the first differing leaf of two JSON documents.
func jsonDiff(got, want string) string {
	var g, w any
	if json.Unmarshal([]byte(got), &g) != nil || json.Unmarshal([]byte(want), &w) != nil {
		return fmt.Sprintf("got  %s\nwant %s", got, want)
	}
	var walk func(path string, g, w any) string
	walk = func(path string, g, w any) string {
		switch wv := w.(type) {
		case map[string]any:
			gv, ok := g.(map[string]any)
			if !ok {
				break
			}
			keys := make([]string, 0, len(wv))
			for k := range wv {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				if d := walk(path+"."+k, gv[k], wv[k]); d != "" {
					return d
				}
			}
			if len(gv) != len(wv) {
				return fmt.Sprintf("%s: keys got %v want %v", path, g, w)
			}
			return ""
		case []any:
			gv, ok := g.([]any)
			if !ok || len(gv) != len(wv) {
				break
			}
			for i := range wv {
				if d := walk(fmt.Sprintf("%s[%d]", path, i), gv[i], wv[i]); d != "" {
					return d
				}
			}
			return ""
		}
		if !reflect.DeepEqual(g, w) {
			gb, _ := json.Marshal(g)
			wb, _ := json.Marshal(w)
			return fmt.Sprintf("%s:\n  got  %s\n  want %s", path, gb, wb)
		}
		return ""
	}
	if d := walk("", g, w); d != "" {
		return d
	}
	return "key order differs:\n  got  " + got + "\n  want " + want
}

func TestIntlNumberGolden(t *testing.T) {
	dir := "testdata/intl/number"
	if soak := os.Getenv("TOOLSCRIPT_INTL_GOLDEN"); soak != "" {
		dir = soak // a larger corpus from golden.mjs <dir> <seed> <scale>
	}
	files := loadIntlGolden(t, filepath.Join(dir, "*.json.gz"))
	reasons := map[string]int{}
	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names)
	total, passed, declined := 0, 0, 0
	for _, name := range names {
		t.Run(name, func(t *testing.T) {
			failures := 0
			for _, c := range files[name] {
				total++
				got, err := runIntlCase(c)
				switch {
				case errors.Is(err, ErrRuntimeUnsupported) && intlAllowedDecline.MatchString(err.Error()):
					declined++
					reasons[err.Error()]++
					continue
				case err != nil:
					failures++
					if failures <= 10 {
						t.Errorf("%s: %v\n%s", c.Name, err, c.Code)
					}
					continue
				case got != c.Want:
					failures++
					if failures <= 10 {
						t.Errorf("%s: %s\n%s", c.Name, jsonDiff(got, c.Want), c.Code)
					}
					continue
				}
				passed++
			}
			if failures > 0 {
				t.Errorf("%s: %d of %d cases differ", name, failures, len(files[name]))
			}
		})
	}
	t.Logf("intl golden: %d cases, %d match Node, %d declined %v", total, passed, declined, reasons)
}

func runNumberScript(t *testing.T, code string) (any, error) {
	t.Helper()
	p, err := Compile(code, options())
	if err != nil {
		t.Fatalf("compile %q: %v", code, err)
	}
	res, err := p.Execute(context.Background(), ExecuteOptions{Dispatch: echo})
	return res.Value, err
}

func TestNumberToLocaleStringWithoutArguments(t *testing.T) {
	// Without locales and options the engine keeps Goja's behavior (the
	// Number's string form), even where V8 would group digits.
	for code, want := range map[string]string{
		`return (1234567.891).toLocaleString()`:                      "1234567.891",
		`return (1234567.891).toLocaleString(undefined, undefined)`:  "1234567.891",
		`return (1234567.891).toLocaleString("en-US")`:               "1,234,567.891",
		`return (0.5).toLocaleString(undefined, {style: "percent"})`: "50%",
	} {
		got, err := runNumberScript(t, code)
		if err != nil || got != want {
			t.Errorf("%s = %v, %v; want %q", code, got, err, want)
		}
	}
}

func TestIntlNumberDeclinesOtherNumberingSystems(t *testing.T) {
	for _, code := range []string{
		`mcp.echo({}); return new Intl.NumberFormat("en-u-nu-arab").format(1)`,
		`return new Intl.NumberFormat("en", {numberingSystem: "thai"}).format(1)`,
		`return (1).toLocaleString("en", {numberingSystem: "deva"})`,
		`return new Intl.RelativeTimeFormat("en-u-nu-beng").format(1, "day")`,
	} {
		if _, err := runNumberScript(t, code); !errors.Is(err, ErrRuntimeUnsupported) {
			t.Errorf("%s: %v, want ErrRuntimeUnsupported", code, err)
		}
	}
	// Unknown (but well-formed) numbering systems fall back to Latin digits.
	got, err := runNumberScript(t, `return new Intl.NumberFormat("en-u-nu-abcd", {numberingSystem: "wxyz"}).format(1234)`)
	if err != nil || got != "1,234" {
		t.Fatalf("got %v, %v", got, err)
	}
}

func TestIntlNumberFormatBoundFormat(t *testing.T) {
	got, err := runNumberScript(t, `const nf = new Intl.NumberFormat("en", {maximumFractionDigits: 1}); const f = nf.format; return [f === nf.format, [1.25, 1000.05].map(nf.format).join("|"), f.length]`)
	if err != nil {
		t.Fatal(err)
	}
	if s := encoded(t, got); s != `[true,"1.3|1,000.1",1]` {
		t.Fatalf("got %s", s)
	}
}
