// Generates intl_number_data.go (CLDR "en" data as ICU ships it in Node)
// for Intl.NumberFormat, Intl.RelativeTimeFormat and friends.
//
//   node internal/intlgen/number/gen.mjs > intl_number_data.go && gofmt -w intl_number_data.go
//
// The data is extracted from the running Node's ICU, so regenerate with the
// Node version the golden tests were made with (see testdata/intl/number).
const out = [];
const w = (s) => out.push(s);
const q = (s) => JSON.stringify(s);

w(`// Code generated by internal/intlgen/number/gen.mjs from Node ${process.version} (ICU ${process.versions.icu}); DO NOT EDIT.`);
w(``);
w(`package toolscript`);
w(``);

// --- currencies ---
const currencyList = Intl.supportedValuesOf("currency");
w(`// intlCurrencyList is Intl.supportedValuesOf("currency").`);
w(`var intlCurrencyList = []string{${currencyList.map(q).join(", ")}}`);
w(``);
const part = (nf, v, type) => nf.formatToParts(v).find((p) => p.type === type).value;
const A = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const cur = [];
for (const a of A) for (const b of A) for (const c of A) {
  const code = a + b + c;
  const sym = part(new Intl.NumberFormat("en", { style: "currency", currency: code }), 1, "currency");
  const nar = part(new Intl.NumberFormat("en", { style: "currency", currency: code, currencyDisplay: "narrowSymbol" }), 1, "currency");
  const one = part(new Intl.NumberFormat("en", { style: "currency", currency: code, currencyDisplay: "name", maximumFractionDigits: 0 }), 1, "currency");
  const other = part(new Intl.NumberFormat("en", { style: "currency", currency: code, currencyDisplay: "name" }), 2, "currency");
  const digits = new Intl.NumberFormat("en", { style: "currency", currency: code }).resolvedOptions().maximumFractionDigits;
  if (sym !== code || nar !== code || one !== code || other !== code || digits !== 2) cur.push([code, digits, sym, nar, one, other]);
}
w(`// intlCurrencyTable holds every ISO 4217 code ICU knows with data other than`);
w(`// the defaults for an unknown code (2 digits, the code as symbol and name).`);
w(`var intlCurrencyTable = map[string]currencyData{`);
for (const [code, digits, sym, nar, one, other] of cur) w(`\t${q(code)}: {${digits}, ${q(sym)}, ${q(nar)}, ${q(one)}, ${q(other)}},`);
w(`}`);
w(``);

// --- units ---
const units = Intl.supportedValuesOf("unit");
const widths = ["long", "short", "narrow"];
const numeric = new Set(["integer", "group", "decimal", "fraction", "minusSign", "compact"]);
const pat = (unit, width, v, notation = "standard") => {
  let s = "";
  let inNum = false;
  for (const p of new Intl.NumberFormat("en", { style: "unit", unit, unitDisplay: width, notation }).formatToParts(v)) {
    if (numeric.has(p.type)) {
      if (!inNum) s += "{0}";
      inNum = true;
    } else {
      s += p.value;
      inNum = false;
    }
  }
  return s;
};
w(`// intlUnitList is Intl.supportedValuesOf("unit").`);
w(`var intlUnitList = []string{${units.map(q).join(", ")}}`);
w(``);
const simple = {};
w(`// intlUnitPatterns: unit -> [long, short, narrow] -> [one, other].`);
w(`var intlUnitPatterns = map[string][3][2]string{`);
for (const u of units) {
  // percent short/narrow use the CLDR unit pattern only in compact notation.
  const n = u === "percent" ? "compact" : "standard";
  simple[u] = widths.map((wd) => [pat(u, wd, 1, n), pat(u, wd, 2, n)]);
  w(`\t${q(u)}: {${simple[u].map((x) => `{${q(x[0])}, ${q(x[1])}}`).join(", ")}},`);
}
w(`}`);
w(``);
// Compound units: numerator pattern + a per-denominator suffix, with exceptions.
const suffix = {};
const exceptions = [];
for (const d of units) {
  suffix[d] = widths.map((wd, wi) => {
    const count = {};
    for (const n of units) {
      const c = pat(`${n}-per-${d}`, wd, 2, n === "percent" ? "compact" : "standard");
      const s = simple[n][wi][1];
      if (c.startsWith(s)) count[c.slice(s.length)] = (count[c.slice(s.length)] || 0) + 1;
    }
    return Object.entries(count).sort((a, b) => b[1] - a[1])[0][0];
  });
  for (const n of units) {
    widths.forEach((wd, wi) => {
      const nt = n === "percent" ? "compact" : "standard";
      const got = [pat(`${n}-per-${d}`, wd, 1, nt), pat(`${n}-per-${d}`, wd, 2, nt)];
      const rule = [simple[n][wi][0] + suffix[d][wi], simple[n][wi][1] + suffix[d][wi]];
      if (got[0] !== rule[0] || got[1] !== rule[1]) exceptions.push([`${n}-per-${d}/${wi}`, got]);
    });
  }
}
w(`// intlUnitPerSuffix: denominator unit -> [long, short, narrow] suffix appended`);
w(`// to the numerator's pattern for "<numerator>-per-<denominator>".`);
w(`var intlUnitPerSuffix = map[string][3]string{`);
for (const d of units) w(`\t${q(d)}: {${suffix[d].map(q).join(", ")}},`);
w(`}`);
w(``);
w(`// intlUnitCompound holds the compound units ICU formats with dedicated data`);
w(`// ("<numerator>-per-<denominator>/<width index>" -> [one, other]).`);
w(`var intlUnitCompound = map[string][2]string{`);
for (const [k, v] of exceptions) w(`\t${q(k)}: {${q(v[0])}, ${q(v[1])}},`);
w(`}`);
w(``);

// --- numbering systems ---
w(`// intlNumberingSystems is Intl.supportedValuesOf("numberingSystem").`);
w(`var intlNumberingSystems = []string{${Intl.supportedValuesOf("numberingSystem").map(q).join(", ")}}`);
w(``);

// --- relative time ---
const rtUnits = ["second", "minute", "hour", "day", "week", "month", "quarter", "year"];
const rtPat = (rtf, v, u) => rtf.formatToParts(v, u).map((p) => (p.type === "literal" ? p.value : "{0}")).join("").replace(/(\{0\})+/, "{0}");
w(`// intlRelativeTimeData: unit -> style [long, short, narrow] ->`);
w(`// [future one, future other, past one, past other, "-1", "0", "1"] where the`);
w(`// last three are the numeric:"auto" phrases.`);
w(`var intlRelativeTimeData = map[string][3][7]string{`);
for (const u of rtUnits) {
  const rows = widths.map((st) => {
    const a = new Intl.RelativeTimeFormat("en", { style: st });
    const b = new Intl.RelativeTimeFormat("en", { style: st, numeric: "auto" });
    for (const v of [-3, -2, 2, 3]) if (/\D/.test(b.format(v, u).replace(/[0-9]/g, "")) && !/[0-9]/.test(b.format(v, u))) throw new Error(`unexpected auto phrase ${u} ${v}`);
    const auto = [-1, 0, 1].map((v) => { const s = b.format(v, u); return /[0-9]/.test(s) ? "" : s; });
    return [rtPat(a, 1, u), rtPat(a, 2, u), rtPat(a, -1, u), rtPat(a, -2, u), ...auto];
  });
  w(`\t${q(u)}: {${rows.map((r) => `{${r.map(q).join(", ")}}`).join(", ")}},`);
}
w(`}`);

console.log(out.join("\n"));
