// Generates intl_tzdata.go: which time zone identifiers V8/ICU accept, what
// each resolves to, and the English zone names ICU prints for each canonical
// zone per year. Run with the Node version recorded in the output:
//
//   node internal/intlgen/tz/gen.mjs > intl_tzdata.go && gofmt -w intl_tzdata.go
import { readFileSync } from "node:fs";

const here = new URL(".", import.meta.url);
const candidates = readFileSync(new URL("candidates.txt", here), "utf8").split("\n").filter(Boolean);
const FIRST = 1970, LAST = 2040;

const resolved = new Map(); // accepted id -> resolved id
for (const id of candidates) {
  try {
    resolved.set(id, new Intl.DateTimeFormat("en-US", { timeZone: id }).resolvedOptions().timeZone);
  } catch {}
}
const canonical = [...new Set(resolved.values())].sort();

const formatters = new Map();
function formatter(tz, style) {
  const key = tz + " " + style;
  if (!formatters.has(key)) formatters.set(key, new Intl.DateTimeFormat("en-US", { timeZone: tz, timeZoneName: style }));
  return formatters.get(key);
}
function offsetSeconds(tz, t) {
  const s = formatter(tz, "longOffset").formatToParts(t).find((p) => p.type === "timeZoneName").value; // GMT, GMT+05:30, GMT-04:56:02
  const m = /^GMT(?:([+-])(\d\d):(\d\d)(?::(\d\d))?)?$/.exec(s);
  if (!m) throw new Error("offset " + s);
  if (!m[1]) return 0;
  const v = +m[2] * 3600 + +m[3] * 60 + +(m[4] || 0);
  return m[1] === "-" ? -v : v;
}
function name(tz, style, t) {
  return formatter(tz, style).formatToParts(t).find((p) => p.type === "timeZoneName").value;
}
const esc = (s) => { if (/[|;]/.test(s)) throw new Error(s); return s; };

// Per zone: runs of years with identical name entries, encoded as
// "from-to|offset|short|long|shortGeneric|longGeneric|offset|...;..." .
const zones = [];
for (const tz of canonical) {
  const runs = [];
  for (let y = FIRST; y <= LAST; y++) {
    // Entries sharing an offset are kept when their names differ (standard
    // and daylight time on one offset, as in Argentina 1999-2000).
    const entries = [];
    for (let month = 0; month < 12; month++) {
      const t = new Date(Date.UTC(y, month, 15, 12));
      const off = offsetSeconds(tz, t);
      const e = [off, name(tz, "short", t), name(tz, "long", t), name(tz, "shortGeneric", t), name(tz, "longGeneric", t)].map(String).map(esc).join("|");
      if (!entries.some((x) => x[1] === e)) entries.push([off, e]);
    }
    const key = entries.sort((a, b) => a[0] - b[0] || (a[1] < b[1] ? -1 : 1)).map((x) => x[1]).join("|");
    const last = runs[runs.length - 1];
    if (last && last.key === key) last.to = y;
    else runs.push({ from: y, to: y, key });
  }
  zones.push([tz, runs.map((r) => `${r.from}-${r.to}|${r.key}`).join(";")]);
}

// Outside ICU's metazone era (before 1970 or from 9999-12-31T23:59Z) names
// fall back to zone-specific names, location formats or GMT offsets. Keyed
// by standard/daylight time: "short|long|shortGeneric|longGeneric" for
// standard then daylight, "@" meaning the GMT offset format.
function gmtText(off, short) {
  if (off === 0) return short ? "GMT+0" : "GMT+00:00";
  const sign = off < 0 ? "-" : "+", a = Math.abs(off);
  const h = Math.floor(a / 3600), m = Math.floor(a / 60) % 60, sec = a % 60;
  const p2 = (n) => String(n).padStart(2, "0");
  let out = "GMT" + sign + (short ? String(h) + (m || sec ? ":" + p2(m) : "") : p2(h) + ":" + p2(m));
  if (sec) out += ":" + p2(sec);
  return out;
}
const pre = [];
for (const tz of canonical) {
  // Classify each pre-1970 year's samples as standard (smaller offset) or
  // daylight (larger), and keep a name only when every sample agrees ("?"
  // otherwise, which the engine declines).
  const seen = [[], []].map(() => [new Set(), new Set(), new Set(), new Set()]);
  for (let y = 1900; y < 1970; y++) {
    const samples = [0, 6].map((month) => {
      const t = new Date(Date.UTC(y, month, 15, 12));
      return [offsetSeconds(tz, t), t];
    });
    const lo = Math.min(samples[0][0], samples[1][0]);
    for (const [off, t] of samples) {
      const dst = off > lo ? 1 : 0;
      ["short", "long", "shortGeneric", "longGeneric"].forEach((style, i) => {
        const v = name(tz, style, t);
        seen[dst][i].add(v === gmtText(off, i % 2 === 0) ? "@" : esc(v));
      });
    }
  }
  const cols = seen.map((styles) => styles.map((set) => (set.size === 1 ? [...set][0] : set.size === 0 ? "" : "?")));
  pre.push([tz, cols[1][0] === "" ? cols[0].join("|") : cols[0].join("|") + "|" + cols[1].join("|")]);
}

const aliases = [...resolved].filter(([id, to]) => id !== to).sort();
const q = JSON.stringify;
let out = `// Code generated by internal/intlgen/tz/gen.mjs with Node ${process.version} (ICU ${process.versions.icu}, tz ${process.versions.tz}); DO NOT EDIT.

package toolscript

const tzFirstYear, tzLastYear = ${FIRST}, ${LAST}

// tzSupported is Intl.supportedValuesOf("timeZone").
var tzSupported = []string{
${Intl.supportedValuesOf("timeZone").map((z) => `\t${q(z)},`).join("\n")}
}

// tzAliases maps accepted non-canonical identifiers to the one ICU resolves.
var tzAliases = map[string]string{
${aliases.map(([a, b]) => `\t${q(a)}: ${q(b)},`).join("\n")}
}

// tzZonePre holds, per resolved zone, the names outside the metazone era:
// "short|long|shortGeneric|longGeneric" (standard) [+ the same for daylight],
// "@" meaning the GMT offset format.
var tzZonePre = map[string]string{
${pre.map(([tz, s]) => `\t${q(tz)}: ${q(s)},`).join("\n")}
}

// tzZoneNames holds, per resolved zone, year runs of the English names ICU
// formats: "from-to|offset|short|long|shortGeneric|longGeneric[|offset|...];...".
var tzZoneNames = map[string]string{
${zones.map(([tz, s]) => `\t${q(tz)}: ${q(s)},`).join("\n")}
}
`;
process.stdout.write(out);
